import type { Purchasable } from "../Purchasable";

export interface Tech extends Purchasable {
  description: string;
  requires?: string[];
  position: number;
}

export const InitialTechs: Tech[] = [
  {
    key: "automation",
    description: "Unlocks robot-based automation",
    costs: [{ resource: "fire", amount: 10 }],
    canAfford: false,
    bought: false,
    position: 0,
    owned: 0,
    max: 1,
    effect: (set) => {},
  },
  {
    key: "solarResearch",
    description: "Increases energy production",
    costs: [{ resource: "air", amount: 100 }],
    canAfford: false,
    bought: false,
    requires: ["automation"],
    position: 1,
    effect: (set) => {},
  },
  {
    key: "advancedAutomation",
    description: "Reduces robot maintenance costs",
    costs: [{ resource: "steam", amount: 300 }],
    canAfford: false,
    bought: false,
    requires: ["automation"],
    position: 1,
    effect: (set) => {},
  },
  {
    key: "aiResearch",
    description: "Enables basic AI processing",
    costs: [{ resource: "water", amount: 500 }],
    canAfford: false,
    bought: false,
    requires: ["advancedAutomation"],
    position: 2,
    effect: (set) => {},
  },
  {
    key: "fusionPower",
    description: "Unlocks fusion reactors for massive energy",
    costs: [{ resource: "fire", amount: 800 }],
    canAfford: false,
    bought: false,
    requires: ["solarResearch", "aiResearch"],
    position: 3,
    effect: (set) => {},
  },

  {
    key: "deepSpaceScanning",
    description: "Unlocks scanning beyond the solar system",
    costs: [{ resource: "energy", amount: 1000 }],
    canAfford: false,
    bought: false,
    requires: ["spacePrep"],
    position: 3,
    effect: (set) => {},
  },
  {
    key: "roboticAssembly",
    description: "Automates assembly lines with robots",
    costs: [{ resource: "steam", amount: 500 }],
    canAfford: false,
    bought: false,
    requires: ["advancedAutomation"],
    position: 2,
    effect: (set) => {},
  },
  {
    key: "solarBattery",
    description: "Improves solar energy storage efficiency",
    costs: [{ resource: "air", amount: 300 }],
    canAfford: false,
    bought: false,
    requires: ["solarResearch"],
    position: 2,
    effect: (set) => {},
  },
  {
    key: "aiOptimization",
    description: "Enhances AI algorithms for efficiency",
    costs: [{ resource: "water", amount: 700 }],
    canAfford: false,
    bought: false,
    requires: ["aiResearch"],
    position: 3,
    effect: (set) => {},
  },
  {
    key: "fusionShielding",
    description: "Improves safety of fusion reactors",
    costs: [{ resource: "fire", amount: 900 }],
    canAfford: false,
    bought: false,
    requires: ["fusionPower"],
    position: 4,
    effect: (set) => {},
  },
  {
    key: "spaceMining",
    description: "Allows extraction of resources from asteroids",
    costs: [{ resource: "fire", amount: 700 }],
    canAfford: false,
    bought: false,
    requires: ["spacePrep", "deepSpaceScanning"],
    position: 4,
    effect: (set) => {},
  },
  {
    key: "quantumComputing",
    description: "Unlocks quantum processors for faster computing",
    costs: [{ resource: "energy", amount: 1500 }],
    canAfford: false,
    bought: false,
    requires: ["aiOptimization", "fusionPower"],
    position: 4,
    effect: (set) => {},
  },
  {
    key: "planetaryTerraforming",
    description: "Begins terraforming nearby planets",
    costs: [{ resource: "fire", amount: 1200 }],
    canAfford: false,
    bought: false,
    requires: ["spaceMining", "fusionShielding"],
    position: 5,
    effect: (set) => {},
  },
  {
    key: "advancedRobotics",
    description: "Develops smarter, multi-purpose robots",
    costs: [{ resource: "steam", amount: 800 }],
    canAfford: false,
    bought: false,
    requires: ["roboticAssembly", "aiOptimization"],
    position: 5,
    effect: (set) => {},
  },
  {
    key: "interstellarCommunication",
    description: "Establishes communication over interstellar distances",
    costs: [{ resource: "energy", amount: 2000 }],
    canAfford: false,
    bought: false,
    requires: ["deepSpaceScanning", "quantumComputing"],
    position: 5,
    effect: (set) => {},
  },

  // Position 6
  {
    key: "warpDrive",
    description: "Develops technology for faster-than-light travel",
    costs: [{ resource: "fire", amount: 2500 }],
    canAfford: false,
    bought: false,
    requires: ["interstellarCommunication", "quantumComputing"],
    position: 6,
    effect: (set) => {},
  },
  {
    key: "nanoFabrication",
    description: "Enables building materials at nanoscale for efficiency",
    costs: [{ resource: "steam", amount: 1500 }],
    canAfford: false,
    bought: false,
    requires: ["advancedRobotics", "fusionShielding"],
    position: 6,
    effect: (set) => {},
  },
  {
    key: "terraformingAdvancement",
    description: "Advanced tech to speed up terraforming processes",
    costs: [{ resource: "fire", amount: 1800 }],
    canAfford: false,
    bought: false,
    requires: ["planetaryTerraforming", "spaceMining"],
    position: 6,
    effect: (set) => {},
  },

  // Position 7
  {
    key: "aiSingularity",
    description: "AI reaches unprecedented capabilities",
    costs: [{ resource: "water", amount: 3000 }],
    canAfford: false,
    bought: false,
    requires: ["aiOptimization", "quantumComputing"],
    position: 7,
    effect: (set) => {},
  },
  {
    key: "dysonSphere",
    description: "Begins construction of a Dyson Sphere to harness star energy",
    costs: [{ resource: "energy", amount: 5000 }],
    canAfford: false,
    bought: false,
    requires: ["fusionPower", "warpDrive"],
    position: 7,
    effect: (set) => {},
  },
  {
    key: "interstellarColonization",
    description: "Enables colonization of distant star systems",
    costs: [{ resource: "fire", amount: 3500 }],
    canAfford: false,
    bought: false,
    requires: ["warpDrive", "terraformingAdvancement"],
    position: 7,
    effect: (set) => {},
  },

  // Position 8
  {
    key: "galacticGovernance",
    description: "Establish a governance system for multi-star civilizations",
    costs: [{ resource: "water", amount: 4500 }],
    canAfford: false,
    bought: false,
    requires: ["interstellarColonization", "aiSingularity"],
    position: 8,
    effect: (set) => {},
  },
  {
    key: "quantumEntanglementComms",
    description: "Instant communication across the galaxy",
    costs: [{ resource: "energy", amount: 6000 }],
    canAfford: false,
    bought: false,
    requires: ["interstellarCommunication", "dysonSphere"],
    position: 8,
    effect: (set) => {},
  },
  {
    key: "stellarEngineering",
    description: "Manipulate stars to create new energy sources and habitats",
    costs: [{ resource: "fire", amount: 7000 }],
    canAfford: false,
    bought: false,
    requires: ["dysonSphere", "terraformingAdvancement"],
    position: 8,
    effect: (set) => {},
  },
];
